movies=[
    {
        title:'Dune',
        genre:'Action',
        src:require('./assets/img/download.jpg'),
    },
    {
        title:'Dune',
        genre:'Action',
        src:require('./assets/img/download.jpg'),
    },
    {
        title:'Dune',
        genre:'Action',
        src:require('./assets/img/download.jpg'),
    },
    {
        title:'Dune',
        genre:'Action',
        src:require('./assets/img/download.jpg'),
    },
];