movies=[
    {
        title:'Dune',
        genre:'Action',
        src:('./assests/img/download.jpg'),
    },
    {
        title:'aa',
        genre:'Action',
        src:('./assests/img/download.jpg'),
    },
    {
        title:'xx',
        genre:'Action',
        src:('./assests/img/download.jpg'),
    },
    {
        title:'cc',
        genre:'Action',
        src:('./assests/img/download.jpg'),
    },
];